services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - '11434:11434'
    networks:
      - dev_network
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    volumes:
      - ollama_data:/root/.ollama
    restart: always
    gpus: all

  pgvector:
    image: pgvector/pgvector:pg18
    container_name: pgvector
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: PASSWORD_ONLY_FOR_DEVELOPMENT
      POSTGRES_DB: emlekezz
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - dev_network

volumes:
  pgvector_data:
  ollama_data:

networks:
  dev_network:
    driver: bridge
