services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - '11434:11434'
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    volumes:
      - ollama_data:/root/.ollama
    restart: always
    gpus: all

  open-webui:
    image: ghcr.io/open-webui/open-webui:cuda
    container_name: open-webui
    ports:
      - '3000:8080'
    environment:
      - WEBUI_AUTH=False
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - open_webui_data:/app/backend/data
    depends_on:
      - ollama
    restart: always
    gpus: all

volumes:
  ollama_data:
  open_webui_data:
