create extension vector;

create table public.note (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  modified_at timestamp with time zone not null default now(),
  title text null,
  content text null,
  embedding vector(768) null,
  user_id uuid not null,
  constraint note_pkey primary key (id),
  constraint note_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;