create extension vector schema extensions;

create table note (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  modified_at timestamp with time zone not null default now(),
  title text null,
  content text null,
  embedding vector(768) null,
  user_id uuid not null,
  constraint note_pkey primary key (id),
  constraint note_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create index user_id
on note
using btree (user_id);

alter table note enable row level security;

create policy "Enable users to view their own data only"
on note
to authenticated
using (
  ( SELECT auth.uid()) = user_id
) with check (
  ( SELECT auth.uid()) = user_id
);